package edu.tum.sse.jtec.reporting;

import edu.tum.sse.jtec.instrumentation.testevent.TestTracingEvent;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.MatchResult;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class TestingLogParser {

    /**
     * Matches the pattern of the test log generated by JTec:
     * Timestamp PID TestEvent [TestSuite] [TestCaseName/Testresults]
     */
    private final Pattern testEventRegex = Pattern.compile("^(\\d+) (\\d+) (\\w+) (.*)$");


    private void parseLogFile(final Map<String, List<TestSuite>> testSuites, final Path testLog) throws IOException {
        final String[] parts = testLog.getFileName().toString().split("_");
        testSuites.putIfAbsent(parts[0], new ArrayList<>());
        final boolean first = true;
        Files.lines(testLog).forEach(line -> {
            final Matcher matcher = testEventRegex.matcher(line);
            if (matcher.find()) {
                final MatchResult result = matcher.toMatchResult();
                final long timestamp = Long.getLong(result.group(0));
                final String PID = result.group(1);
                final TestTracingEvent event = TestTracingEvent.valueOf(result.group(2));

                switch (event) {
                    case TEST_FINISHED:
                    case TEST_STARTED:
                        // Relevant for handling individual test cases later
                        break;
                    case SUITE_FINISHED:
                        result.group(3).split(" ");
                }
            }
        });
    }

}
